name: Update Python Offsets

on:
  schedule:
    - cron: "5 10 * * 1"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-python-offsets:
    runs-on: ubuntu-latest
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
          detached: true

      - uses: actions/checkout@v7
        with:
          persist-credentials: 'false'
          ref: ebpf/python-offsets-test-ci
          submodules: recursive

      - name: Update offsets
        working-directory: ebpf
        run: |
          make python/dwarfdump
          make glibc/dwarfdump
          make musl/dwarfdump

      - name: Update ebpf/testdata submodule
        working-directory: ebpf/testdata
        run: |
          git config pull.rebase true
          git pull

      - name: Verify Changed files
        id: verify-changed-files
        run: |
          git status
          git diff
          # If there are no changes exit code will be 0 and 1 if there are changes
          if git diff --exit-code ebpf/python/glibc*.go ebpf/python/musl*.go ebpf/python/python*.go > /dev/null; then
              echo "files_changed=false" >> $GITHUB_OUTPUT
          else
              echo "files_changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git config --local user.email "bot@ceems.com"
          git config --local user.name "CEEMS Bot"
          git add -A
          git commit -m "chore: Update Python/MUSL/GLIBC dwarfdumps" -s
          git status

      - name: Push changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ebpf/python-offsets-test-ci
          push_to_submodules: on-demand
